// This file is generated by Slice Machine. Update with care!

import ConteudoApresentacao from './ConteudoApresentacao';
import ConteudoFormaIngresso from './ConteudoFormaIngresso';
import Curso from './Curso';
import Docente from './Docente';
import GrupoPesquisa from './GrupoPesquisa';
import LinksFormaIngresso from './LinksFormaIngresso';
import Livro from './Livro';
import Membro from './Membro';
import Post from './Post';
import RevistaOuPublicacao from './RevistaOuPublicacao';
import SetoresInstancias from './SetoresInstancias';

export {
	ConteudoApresentacao,
	ConteudoFormaIngresso,
	Curso,
	Docente,
	GrupoPesquisa,
	LinksFormaIngresso,
	Livro,
	Membro,
	Post,
	RevistaOuPublicacao,
	SetoresInstancias,
};

export const components = {
	conteudo_apresentacao: ConteudoApresentacao,
	conteudo_forma_ingresso: ConteudoFormaIngresso,
	curso: Curso,
	docente: Docente,
	grupo_pesquisa: GrupoPesquisa,
	links_forma_ingresso: LinksFormaIngresso,
	livro: Livro,
	membro: Membro,
	post: Post,
	revista_ou_publicacao: RevistaOuPublicacao,
	setores_instancias: SetoresInstancias,
};
