// This file is generated by Slice Machine. Update with care!

import ConteudoFormaIngresso from './ConteudoFormaIngresso';
import Membro from './Membro';
import Post from './Post';

export {
	ConteudoFormaIngresso,
	Membro,
	Post,
};

export const components = {
	conteudo_forma_ingresso: ConteudoFormaIngresso,
	membro: Membro,
	post: Post,
};
